name: Test
on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Dependency Check
        run: npm run depcheck
      - name: Build
        run: npm run build
      - name: ESlint
        run: npm run lint
      - name: Seed Database
        run: npx ts-node scripts/seed.ts
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      - name: Tests
        run: npm test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          GOOGLE_OAUTH_CLIENT_ID: 425704804623-04q55nmf47je6ejqua6b252t5dtptkfr.apps.googleusercontent.com
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_OAUTH_CALLBACK_URL: http://localhost:3000/auth/google/callback
          PORT: 3000
      - name: Upload Coverage Reports
        run: bash <(curl -s https://codecov.io/bash)
